server:
  address: localhost
  port: 9001

spring:
  application:
    name: eureka-provider

eureka:
  instance:
    ## 是否将自己的 ip 地址注册到 eureka
#    prefer-ip-address: true
    ## 客户端 id
    instance-id: ${server.address}:${server.port}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
