server:
  address: localhost
  port: 8082

spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          name: order-service
        username: admin
        password: admin
#        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always